version: "3"

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./scripts/init-pg.sql:/docker-entrypoint-initdb.d/init-pg.sql
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: abcd1234
